name: Build & Publish to GH Pages
on:
  release:
    types: [published]
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    # Only run on releases with tags matching publish-*
    if: github.event_name == 'workflow_dispatch' || startsWith(github.ref, 'refs/tags/publish-')
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/quantecon/quantecon-build:latest
    permissions:
      contents: read
      packages: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Restore Jupyter Cache
        uses: quantecon/actions/restore-jupyter-cache@v0.6.0
      
      - name: Build HTML
        uses: quantecon/actions/build-lectures@v0.6.0
        id: build
        with:
          builder: 'html'
          upload-failure-reports: true
      
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: html-build
          path: ${{ steps.build.outputs.build-path }}
          retention-days: 7
      
      - name: Create ZIP Archive
        if: startsWith(github.ref, 'refs/tags/publish-')
        run: |
          cd ${{ steps.build.outputs.build-path }}
          zip -r ../lecture-dp-html.zip .
      
      - name: Upload to Release
        if: startsWith(github.ref, 'refs/tags/publish-')
        uses: softprops/action-gh-release@v2
        with:
          files: _build/lecture-dp-html.zip
          fail_on_unmatched_files: true

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page-url }}
    steps:
      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: html-build
          path: _build/html
      
      - name: Deploy to GitHub Pages
        id: deployment
        uses: quantecon/actions/publish-gh-pages@v0.6.0
        with:
          build-dir: _build/html
