name: Build & Publish to GH Pages
on:
  release:
    types: [published]
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  publish:
    # Only run on releases with tags matching publish-*
    if: github.event_name == 'workflow_dispatch' || startsWith(github.ref, 'refs/tags/publish-')
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page-url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Setup Environment
        uses: quantecon/actions/setup-environment@v0.6.0
      
      - name: Build HTML
        uses: quantecon/actions/build-lectures@v0.6.0
        id: build
        with:
          builder: 'html'
          upload-failure-reports: true
      
      - name: Deploy to GitHub Pages
        id: deploy
        uses: quantecon/actions/publish-gh-pages@v0.6.0
        with:
          build-dir: ${{ steps.build.outputs.build-path }}
